### ISSUE TITLE
Grid: responsive

### ISSUE THREAD

**Issue by gehalber** [everythingtype/etc-nyc#50]
With the large thumbnail version used only, the grid isn't super responsive to the browser width.
Is there a way we could get the grid to respond to the browser width in a more fluid way? Perhaps if the images scaled down first, then popped to one column at a certain breakpoints. Right now, then just pop to one column with a lot of margin space left over.

Maybe we should talk about it...

**Comment by halfempty** [comment]
@gehalber It is possible to change how these work, but it'll take a bit of tinkering. It means rebuilding the thumbnail code.

I get the sense you're hot to launch. Would you like to launch it as-is, and then continue to work on this aspect? Or would you like this changed before launch?

**Comment by gehalber** [comment]
Yeah, that’s what I figured. 
Let’s launch and build this out on the fly.

Trying to be more agile in my old age.

Thanks Marty!

**Comment by halfempty** [comment]
@gehalber Hi there. Made a bit of progress on making the grid responsive, here:

http://revision.etc-nyc.com/everything/

Is it rendering okay for you? (I still need to test it on a PC, as well.)

At what sizes would you like it to switch between 1, 2, 3, etc columns?

One major caveat is that it's depending on the thumbnails being as wide as their containing box. Because all our thumbs are this way now I've gone ahead with it, but when you're ready to add portrait-sized thumbs again we'll need to revisit. (This is because of Firefox by the way. The related bug doesn't appear in Chrome/Safari.)

Additionally, in doing this I may have broken the "related projects" bit, currently unused. I'll have to take another look at them when it's time to bring them back.

**Comment by halfempty** [comment]
@gehalber Okay, I've applied this. I've set the switch from 1 column to 2 at 1000px, let me know if you'd like this tweaked.
